### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by yodahuang** [rctoris/mjpegcanvasjs#33]
Hi, can you publish this package on npm or add `main` field in `package.json` so that we can manage this package together with many others using npm?

**Comment by yodahuang** [comment]
Oops it's BSD licence so I can just do that all myself.

**Comment by escrowdis** [comment]
> Oops it's BSD licence so I can just do that all myself.

Hi @yodahuang,

Really happy to see someone using this package. Did you upload this on npm?

Thanks!

**Comment by yodahuang** [comment]
I didn't do it since I pivoted to another project. But it's always good to get this nice work published.

**Comment by escrowdis** [comment]
That's great! I just uploaded [0.4.0 version](https://www.npmjs.com/package/mjpegcanvas)
`npm i mjpegcanvas` for anyone who might need this one
